SELECT A.AUTHOR_ID,	A.AUTHOR_NAME, B.CATEGORY, sum(B.PRICE * S.SALES) as TOTAL_SALES
from BOOK as B
    join AUTHOR as A on A.AUTHOR_ID = B.AUTHOR_ID
    join BOOK_SALES as S on S.BOOK_ID = B.BOOK_ID and S.SALES_DATE like "2022-01%"
group by B.CATEGORY, A.AUTHOR_ID
order by A.AUTHOR_ID, B.CATEGORY desc;