-- 코드를 입력하세요
SELECT 
    PRODUCT.PRODUCT_CODE, 
    sum(OFFLINE_SALE.SALES_AMOUNT * PRODUCT.PRICE) as SALES
from PRODUCT 
    join OFFLINE_SALE
    on PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
group by PRODUCT.PRODUCT_CODE
order by SALES desc, PRODUCT.PRODUCT_CODE asc;