-- 코드를 입력하세요
SELECT I.REST_ID,I.REST_NAME,I.FOOD_TYPE,I.FAVORITES,I.ADDRESS, round(avg(R.REVIEW_SCORE),2) as REVIEW_SCORE
from REST_INFO as I
join REST_REVIEW as R
    on I.REST_ID = R.REST_ID
where I.ADDRESS like "서울%"
group by I.REST_ID
order by REVIEW_SCORE desc, I.FAVORITES desc;