WITH CAR_TOTAL_RENTALS AS (
    -- 자동차별 총 대여 횟수 계산
    SELECT CAR_ID, COUNT(*) AS TOTAL_RENTALS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE YEAR(START_DATE) = 2022
        AND MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING TOTAL_RENTALS >= 5
), MONTHLY_CAR_RENTALS AS (
    -- 월별 자동차 ID별 대여 횟수 계산
    SELECT 
        MONTH(START_DATE) AS MONTH, 
        CAR_ID, 
        COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE YEAR(START_DATE) = 2022
        AND MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY MONTH(START_DATE), CAR_ID
)
-- 최종 결과: 5회 이상 대여된 자동차만 포함
SELECT M.MONTH, M.CAR_ID, M.RECORDS
FROM MONTHLY_CAR_RENTALS M
JOIN CAR_TOTAL_RENTALS T ON M.CAR_ID = T.CAR_ID
ORDER BY M.MONTH ASC, M.CAR_ID DESC;
